name: voila-example
channels:
  - conda-forge
dependencies:
  - altair
  - pandas
  - jupyter
  - ipyvuetify
  - voila
  - matplotlib
  - nbconvert
  - python=3.8
  - scipy 
  - scikit-learn
  - voila-gridstack
  - voila-material
  - voila-vuetify